#!/usr/bin/python
import os

offline = False
try:
    virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/' or 'none!!'
    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    print 'IOError: Reading virtualenv.'
except:
    print ('You\'re working offline')
    offline = True

#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

def application(environ, start_response):

    ctype = 'text/plain'
    if environ['PATH_INFO'] == '/health':
        response_body = "1"
    elif environ['PATH_INFO'] == '/env':
        response_body = ['%s: %s' % (key, value)
                    for key, value in sorted(environ.items())]
        response_body = '\n'.join(response_body)
    elif offline and environ['PATH_INFO'] == '/static':
        ctype = 'text/html'
        response_body = "You are trying to access static files"
    else:
        ctype = 'text/html'
        file = open('static/index.html','r')
        response_body = file.read()

    status = '200 OK'
    response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
    #
    start_response(status, response_headers)
    return [response_body]

#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.serve_forever()

