#!/usr/bin/python
import os

openshift = True
try:
    virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/' or 'none!!'
    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    print 'IOError: Reading virtualenv.'
except:
    print ('You\'re working offline')
    openshift = False

#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 
import re

def application(environ, start_response):
    path = environ['DOCUMENT_ROOT']+'/' if openshift else environ['PWD']+"/"
    ctype = 'text/plain'
    if environ['PATH_INFO'] == '/health':
         response_body = "1"
    elif environ['PATH_INFO'] == '/env':
        response_body = ['%s: %s' % (key, value)
                    for key, value in sorted(environ.items())]
        response_body = '\n'.join(response_body)
    elif not openshift and re.match(r"/static/(.*)",environ['PATH_INFO'],re.M|re.I):
        ctypes = {
            'css':'text/css',
            'html':'text/html',
            'js':'application/javascript',
            'txt':'text/plain'
        }
        ctype = 'text/plain'
        file = environ['PATH_INFO'].split("/")
        file = file[len(file)-1]
        ext = file.split(".")
        ext = ext[len(ext)-1]
        ctype_ext = ctypes.get(ext)
        if(ctype_ext == None):
            try:
                file = open(path+environ['PATH_INFO'][1:])
                response_body = file.read()
            except IOError:
                response_body = '404. The file could not be found.'
        else:
            try:
                ctype = ctypes[ext]
                file = open(path+environ['PATH_INFO'][1:])
                response_body = file.read()
            except IOError:
                response_body = '404. The file could not be found.'
    else:
        ctype = 'text/html'
        try:
            file = open(path+'static/index.html','r')
            response_body = file.read()
        except IOError,e:
            response_body = "could not read file "+path+"/static/__file__ --("+__file__+")\nError: "+str(e)            

    status = '200 OK'
    response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
    #
    start_response(status, response_headers)
    return [response_body]

#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Serve requests until server stops. Use .handle_request() for a single use
    httpd.serve_forever()

